### ISSUE TITLE
The manifest.Properties is nil.

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry-incubator/greenhouse-install-script-generator#3]
When i use the latest version generator : 

```
generate.exe -boshUrl https://director:xxxxxxxx@10.10.130.102:25555 -outputDir c:/diego -windowsPassword ddd -windowsUsername ddd
```

output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x402363]

goroutine 1 [running]:
main.fillSharedSecret(0xc08206dee8, 0xc082000a80, 0x25, 0x25, 0x0)
C:/diego-windows-release/greenhouse-install-script-generator/src/generat
e/generate.go:151 +0x93
main.main()
C:/diego-windows-release/greenhouse-install-script-generator/src/generat
e/generate.go:124 +0xc97

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08204c0b0)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08204c0b0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3
```

And i found generator.go :

```
func fillSharedSecret(args *models.InstallerArguments, manifest models.Manifest) {
        repJob := firstRepJob(manifest)
        properties := repJob.Properties
        if properties.MetronEndpoint == nil {
                fmt.Println(manifest.Properties)
                properties = manifest.Properties
        }
        args.SharedSecret = properties.MetronEndpoint.SharedSecret
}
```

The manifest.Properties return nil.

**Comment by mhoran** [comment]
Hi @wdxxs2z,

Our current workflow for keeping the generator synchronized with the manifest of CF/Diego deployments is to bundle the generator with releases of https://github.com/cloudfoundry/diego-windows-release. I would guess your error is from using the most recent generator with an older CF deployment that still had the Metron shared secret inside of Loggregator's config. We made this change here: https://github.com/cloudfoundry-incubator/greenhouse-install-script-generator/commit/c7861c1717d4bd0b1958892debcdc149a6aa9429.

You can try recompiling it from the older source, or find a diego-windows-release that's compatible with your CF/Diego release and use the generator from it.

Feel free to reopen if this you continue to have problems. In that case, it would be useful to see your manifest to confirm our ideas, just make sure you scrub the secrets out of it before posting it on here.
