### ISSUE TITLE
extractMetronKeyAndCert failing on cf 233

### ISSUE THREAD

**Issue by jleavers** [cloudfoundry-incubator/greenhouse-install-script-generator#5]
Currently generate.exe is failing when it tries to extract metron_ca.crt.

This could be because the BOSH properties changed in cf 231?

metron_agent.tls_client.key --> metron_agent.tls.client_key
metron_agent.tls_client.cert --> metron_agent.tls.client_cert
loggregator.tls.ca --> loggregator.tls.ca_cert

**Comment by mhoran** [comment]
Thanks for the heads up! We've pushed a fix in a6fd900f3bc26f01af3de2efe743c174d24d8261. This should be included in the next diego-windows-release release.
